# WHY: Prevent maintenance from breaking your app
# PROBLEM: Node maintenance could take down too many pods at once
# SOLUTION: PDB ensures minimum pods stay running during voluntary disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb
spec:
  minAvailable: 3        # Keep at least 3 pods running
  # Alternative: maxUnavailable: 2  # Allow max 2 pods to be unavailable
  selector:
    matchLabels:
      app: webapp
      
# Usage scenarios:
# - Node drain: PDB prevents draining too many pods at once
# - Rolling updates: PDB ensures availability during updates
# - Cluster maintenance: PDB maintains service availability