# VPA Recommendation-Only Mode
# WHY: Safer approach - get sizing recommendations without automatic updates
# WHEN: Use in production to understand resource patterns before enabling auto-updates

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-app
  template:
    metadata:
      labels:
        app: analysis-app
    spec:
      containers:
      - name: analysis-app
        image: nginx:1.21
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 80

---
# VPA in recommendation-only mode
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: analysis-app-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analysis-app
  
  updatePolicy:
    updateMode: "Off"         # Only provides recommendations, no automatic updates
  
  resourcePolicy:
    containerPolicies:
    - containerName: analysis-app
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
      
      # Control which resource values VPA manages
      controlledValues: RequestsAndLimits
      
      # Optional: Set ratio between limits and requests
      # maxAllowed and minAllowed apply to requests
      # Limits will be calculated based on this ratio
      # If not specified, VPA will set limits = requests * 1.5 (for CPU) or * 1.2 (for memory)

---
# How to check VPA recommendations:
# kubectl describe vpa analysis-app-vpa
# kubectl get vpa analysis-app-vpa -o yaml
#
# Look for:
# status:
#   recommendation:
#     containerRecommendations:
#     - containerName: analysis-app
#       target:          # Recommended values
#         cpu: "150m"
#         memory: "300Mi"
#       lowerBound:      # Minimum recommended
#         cpu: "100m"
#         memory: "200Mi"
#       upperBound:      # Maximum recommended
#         cpu: "200m"
#         memory: "400Mi"