# WHY: Need internal communication between services
# PROBLEM: Pods have changing IPs, need stable endpoint
# SOLUTION: ClusterIP provides fixed internal address
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP  # Default type
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP