# NodePort Service - External Access via Node IP
# Accessible from outside cluster using NodeIP:30080
# Example: http://172.16.0.2:30080
apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 80          # Service port
    targetPort: 80    # Pod port
    nodePort: 30080   # External port on all nodes
    protocol: TCP