# WHY: Need simple external access for testing/development
# PROBLEM: ClusterIP only works inside cluster
# SOLUTION: NodePort opens port on every node for external access
apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 80          # Service port
    targetPort: 80    # Pod port
    nodePort: 30080   # External port on all nodes
    protocol: TCP