# WHY: Need production-grade external access
# PROBLEM: NodePort requires manual load balancing
# SOLUTION: Cloud provider creates managed load balancer
apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 80          # External port
    targetPort: 80    # Pod port
    protocol: TCP
# Cloud provider creates external load balancer
# pointing to all nodes on automatically assigned nodePort